### ISSUE TITLE
Array initialization

### ISSUE THREAD

**Issue by bennySim** [DolajoCZ/Noughts-And-Crosses#1]
https://github.com/DolajoCZ/Noughts-And-Crosses/blob/b55b0d17c3813db6ffe09e4850a7338a66f425b4/src/game/field.rs#L159-L169

Môže byť nahradené zápisom:
```
fields: [SingleField::new(); 9];
```

**Comment by DolajoCZ** [comment]
Upraveno v [tomto](https://github.com/DolajoCZ/Noughts-And-Crosses/commit/222f9b291818c692f9d1dacd1f48f7a93791e756) commitu. Díky za zpřehleďnující tip.

**Comment by bennySim** [comment]
Ked v commite napises #number tak to prida zmienku aj sem. Ak pridas aj klucove slova ako napr fixes #number tak to dokonca aj zatvori issue. Viac info [tu](https://github.blog/2011-04-09-issues-2-0-the-next-generation/).

**Comment by DolajoCZ** [comment]
Díky za tip. Toto jsem nevěděl. Uvidíme jestli to budu používat, neboť tento a všechny ostatní osobní projekty udržuji ve svém Gitlabu a zde dochází pouze k synchronizaci. Když pak použiji uvedený styl, tak se budu odkazovat na neexistující issue na Gitlabu, což může působit zmatečně, i když to tu na Githubu bude všechno fungovat.

Stejně tak musím vymyslet jak s pipeline, protože si ji chci napsat pro Rust+Gitlab. Kontrola formátování, obecné Rust konvence, docstring + generování dokumentace, unittesty, coverage a jeho report na Gitlab pages atd...
