### ISSUE TITLE
Inability to change port

### ISSUE THREAD

**Issue by fajlip** [DolajoCZ/Noughts-And-Crosses#10]
https://github.com/DolajoCZ/Noughts-And-Crosses/blob/b55b0d17c3813db6ffe09e4850a7338a66f425b4/src/main.rs#L62

Bylo by lepší, kdyby port nebyl zadaný napevno ve zdrojovém kódu, ale mohl být volen uživatelem. Důvodem proto je skutečnost, že port může používat jiná aplikace.

**Comment by DolajoCZ** [comment]
Upraveno v [tomto](https://github.com/DolajoCZ/Noughts-And-Crosses/commit/b2cd861b2c6da3dbb8f5abfcc1f2b68ad6e4fad3) commitu. Díky za vylepšení.
