### ISSUE TITLE
Struct state reset

### ISSUE THREAD

**Issue by fajlip** [DolajoCZ/Noughts-And-Crosses#11]
https://github.com/DolajoCZ/Noughts-And-Crosses/blob/b55b0d17c3813db6ffe09e4850a7338a66f425b4/src/game/field.rs#L212

Netřeba iterovat přes celé vnitřní pole a nulovat jednu položku po druhé. O něco vhodnějším řešením by mohlo být využití tvorby nového objektu a přiřazení výchozích hodnot; což se může hodit i v budoucnu, kdyby proměnných přibývalo, přestože je to asi nepravděpodobný scénář.

`self.fields = Field::new().fields;`

**Comment by DolajoCZ** [comment]
Stejné issue jako [toto](https://github.com/DolajoCZ/Noughts-And-Crosses/issues/18).
