### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by bennySim** [DolajoCZ/Noughts-And-Crosses#17]
Pridat konštanty napriklad na velkost pola

**Comment by DolajoCZ** [comment]
Děkuji za dobrý nápad. V rámci [tohoto](https://github.com/DolajoCZ/Noughts-And-Crosses/commit/bc71a7eb414d6c8010f0d9c228e2731c8e57f541) commitu již ovšem není velikost pole pevně daná, takže toto nemohu aplikovat.
