### ISSUE TITLE
Playerboard::new_move separate parsing and passing argument

### ISSUE THREAD

**Issue by bennySim** [DolajoCZ/Noughts-And-Crosses#23]
Parsing coordinates should be tied to GUI not to PlayerBoard function, consider changing new_move functionality to only resolving parsed arguments. 
Coordinates can be defined using traits.

**Comment by DolajoCZ** [comment]
Uvedená funkcionalita by měla být zakomponována v [tomto](https://github.com/DolajoCZ/Noughts-And-Crosses/commit/8f514dff7c25541098fad7577024637abb1104fd) comitu. Prosím o validaci.

Děkuji za návrh, který vedl k lepšímu kódu.
