### ISSUE TITLE
Iter vs. Init

### ISSUE THREAD

**Issue by bennySim** [DolajoCZ/Noughts-And-Crosses#6]
https://github.com/DolajoCZ/Noughts-And-Crosses/blob/b55b0d17c3813db6ffe09e4850a7338a66f425b4/src/game/field.rs#L212

Nie je čitateľnejšie nahradiť novým polom?
```
self.fields = [SingleField::new(); 9];
```

**Comment by DolajoCZ** [comment]
V rámci [tohoto](https://github.com/DolajoCZ/Noughts-And-Crosses/commit/69b0c84460ab09644de520c3bb2f0270a80e15d4) commitu a [toho](https://github.com/DolajoCZ/Noughts-And-Crosses/issues/18) issue jsem uvedený řádek odstranil.
