### ISSUE TITLE
Playboard formatting

### ISSUE THREAD

**Issue by bennySim** [DolajoCZ/Noughts-And-Crosses#7]
https://github.com/DolajoCZ/Noughts-And-Crosses/blob/b55b0d17c3813db6ffe09e4850a7338a66f425b4/src/game/field.rs#L218-L240

Dovolim si tvrdit, ze [moje riesenie](https://github.com/bennySim/tictactoe/blob/master/src/main.rs#L199-L206) je trosku prehladnejsie zapisane.

**Comment by DolajoCZ** [comment]
V rámci dosažení dostatečné obecnosti na vstupu funkce 'run_game' jsem uvedený přístup opustil a nahradil obecným řešením v [tomto](https://github.com/DolajoCZ/Noughts-And-Crosses/commit/8f514dff7c25541098fad7577024637abb1104fd) commitu. Prosím o revizi, děkuji.
