### ISSUE TITLE
Duplicate content for send message functions

### ISSUE THREAD

**Issue by fajlip** [DolajoCZ/Noughts-And-Crosses#9]
https://github.com/DolajoCZ/Noughts-And-Crosses/blob/b55b0d17c3813db6ffe09e4850a7338a66f425b4/src/game/msgs.rs#L10

Funkce sloužící k odeslání zpráv jednotlivým hráčům mají prakticky stejné chování. Bylo by tedy lepší funkci napsat jednou a zprávu brát jako vstupní parametr. Pokud bych nechtěl volajícího nutit použít řetězec, pak by mi přišlo vhodné volit typ zprávy nějakým enumem.

**Comment by DolajoCZ** [comment]
Zasílání zpráv uživateli jsem přepracoval dle návrhu na enum. Výsledné změny jsou v [tomto](https://github.com/DolajoCZ/Noughts-And-Crosses/issues/9) commitu.
